/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Client;

/**
 *
 * @author Usuario
 */
public class CreacionDePersonaje extends javax.swing.JPanel {

    /**
     * Creates new form CreacionDePersonaje
     */
    public CreacionDePersonaje() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jToggleButton1 = new javax.swing.JToggleButton();
        jToggleButton2 = new javax.swing.JToggleButton();
        jToggleButton3 = new javax.swing.JToggleButton();
        jLabel1 = new javax.swing.JLabel();
        jToggleButton4 = new javax.swing.JToggleButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jComboBox2 = new javax.swing.JComboBox<>();
        jComboBox3 = new javax.swing.JComboBox<>();
        jComboBox4 = new javax.swing.JComboBox<>();
        jLabel9 = new javax.swing.JLabel();
        jComboBox5 = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextPane1 = new javax.swing.JTextPane();
        jSeparator1 = new javax.swing.JSeparator();
        jButton1 = new javax.swing.JButton();

        jPanel2.setBackground(new java.awt.Color(0, 0, 0));
        jPanel2.setLayout(null);

        jToggleButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/SirenaNew.png"))); // NOI18N
        jToggleButton1.setText("jToggleButton1");
        jPanel2.add(jToggleButton1);
        jToggleButton1.setBounds(740, 400, 220, 220);

        jToggleButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/cutuluNew.png"))); // NOI18N
        jToggleButton2.setText("jToggleButton1");
        jPanel2.add(jToggleButton2);
        jToggleButton2.setBounds(20, 400, 220, 220);

        jToggleButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/mantaNew.png"))); // NOI18N
        jToggleButton3.setText("jToggleButton1");
        jPanel2.add(jToggleButton3);
        jToggleButton3.setBounds(260, 400, 220, 220);

        jLabel1.setFont(new java.awt.Font("Roboto", 0, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(204, 204, 204));
        jLabel1.setText("Creacion de luchadores");
        jPanel2.add(jLabel1);
        jLabel1.setBounds(10, 0, 380, 50);

        jToggleButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/poseidonNew.png"))); // NOI18N
        jToggleButton4.setText("jToggleButton1");
        jPanel2.add(jToggleButton4);
        jToggleButton4.setBounds(500, 400, 220, 220);

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        jPanel1.setLayout(null);

        jLabel2.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Autosanidad");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(10, 250, 120, 40);

        jLabel4.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Nombre:");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(10, 10, 80, 30);

        jLabel5.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Estadisticas");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(10, 140, 100, 22);

        jLabel6.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Grupo de ataque:");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(10, 50, 140, 30);

        jLabel7.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Poder");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(10, 170, 80, 40);

        jLabel8.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Resistencia");
        jPanel1.add(jLabel8);
        jLabel8.setBounds(10, 210, 100, 40);

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "50%", "30%", "20%", " " }));
        jPanel1.add(jComboBox1);
        jComboBox1.setBounds(360, 90, 90, 30);

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "100%", "75%", "50%", " " }));
        jPanel1.add(jComboBox2);
        jComboBox2.setBounds(360, 260, 90, 30);

        jComboBox3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "100%", "75%", "50%", " " }));
        jPanel1.add(jComboBox3);
        jComboBox3.setBounds(360, 220, 90, 30);

        jComboBox4.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Thunders Under The Sea", "Fish Thelepathy", "Release the Kraken", "Waves Control", "The Trident", "Undersea volcanos" }));
        jPanel1.add(jComboBox4);
        jComboBox4.setBounds(260, 50, 190, 30);

        jLabel9.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Porcentaje de representacion: ");
        jPanel1.add(jLabel9);
        jLabel9.setBounds(10, 90, 260, 30);

        jComboBox5.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "100%", "75%", "50%", " " }));
        jPanel1.add(jComboBox5);
        jComboBox5.setBounds(360, 180, 90, 30);

        jScrollPane1.setViewportView(jTextPane1);

        jPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(260, 10, 190, 30);
        jPanel1.add(jSeparator1);
        jSeparator1.setBounds(10, 160, 100, 10);

        jPanel2.add(jPanel1);
        jPanel1.setBounds(10, 70, 460, 310);

        jButton1.setText("Crear luchador");
        jPanel2.add(jButton1);
        jButton1.setBounds(480, 320, 190, 60);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 978, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 619, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JComboBox<String> jComboBox3;
    private javax.swing.JComboBox<String> jComboBox4;
    private javax.swing.JComboBox<String> jComboBox5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextPane jTextPane1;
    private javax.swing.JToggleButton jToggleButton1;
    private javax.swing.JToggleButton jToggleButton2;
    private javax.swing.JToggleButton jToggleButton3;
    private javax.swing.JToggleButton jToggleButton4;
    // End of variables declaration//GEN-END:variables
}
